name: build

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  watch:
    types: [started]

permissions:
  contents: write
  packages: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          cache: true

      - name: Test
        run: go test -v ./...

  goreleaser:
    name: Build and publish Go binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          cache: true

      - name: Run GoReleaser build
        uses: goreleaser/goreleaser-action@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot

      - name: Run GoReleaser build and publish tags
        uses: goreleaser/goreleaser-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: omegabrr
          path: |
            dist/*.tar.gz
            dist/*.json
            dist/*.yaml
